### PR TITLE
Prices

### PR DESCRIPTION
**Pull request by badger-99**
I have made the following changes in this branch:
- The new workspace form now requires a price per day to be included to create a Workspace
- Workspaces in the home and details pages show the Price Per Day
- When making a reservation in both the workspace details and the reservation form, the reservation cost is reflected dynamically depending on the selected workspace and dates but it is not sent to the server. The back end performs the same operation to calculate the reservation cost and saves it to the database to avoid malicious actors from manipulating the costs.
- The reservations page shows the cost of each reservation.

### CODE REVIEW

**Comment by Zilola-Nazarova** [comment]
Here's your favourite linter)))

**Comment by badger-99** [comment]
> Here's your favourite linter)))

# 🥲

**Comment by badger-99** [comment]
Thank you for the assistance with the linters, I had trouble spotting them in my system!

**Review by Zilola-Nazarova — APPROVED** [review]
I have tested these new features and everything works as expected.
You can merge it!

**Pull request merged**
